import js
js.globals['python']['schedulers'] = [{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.BF', 'name': 'simso.schedulers.BF'},
{'required_proc_fields': [{'default': '1.0', 'type': 'float', 'name': 'speed'}], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.CC_EDF', 'name': 'simso.schedulers.CC_EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.DP_WRAP', 'name': 'simso.schedulers.DP_WRAP'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDCL', 'name': 'simso.schedulers.EDCL'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDF', 'name': 'simso.schedulers.EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDF2', 'name': 'simso.schedulers.EDF2'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDF_US', 'name': 'simso.schedulers.EDF_US'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDF_mono', 'name': 'simso.schedulers.EDF_mono'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDHS', 'name': 'simso.schedulers.EDHS'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EDZL', 'name': 'simso.schedulers.EDZL'},
{'required_proc_fields': [], 'required_fields': [{'default': '0', 'type': 'int', 'name': 'K'}], 'required_task_fields': [], 'display_name': 'simso.schedulers.EKG', 'name': 'simso.schedulers.EKG'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.EPDF', 'name': 'simso.schedulers.EPDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.ER_PD2', 'name': 'simso.schedulers.ER_PD2'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [{'default': '0', 'type': 'int', 'name': 'priority'}], 'display_name': 'simso.schedulers.FP', 'name': 'simso.schedulers.FP'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.Fixed_PEDF', 'name': 'simso.schedulers.Fixed_PEDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.G_FL', 'name': 'simso.schedulers.G_FL'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.G_FL_ZL', 'name': 'simso.schedulers.G_FL_ZL'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.LB_P_EDF', 'name': 'simso.schedulers.LB_P_EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.LLF', 'name': 'simso.schedulers.LLF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.LLREF', 'name': 'simso.schedulers.LLREF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.LLREF2', 'name': 'simso.schedulers.LLREF2'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.LRE_TL', 'name': 'simso.schedulers.LRE_TL'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.MLLF', 'name': 'simso.schedulers.MLLF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.NVNLF', 'name': 'simso.schedulers.NVNLF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.PD2', 'name': 'simso.schedulers.PD2'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.P_EDF', 'name': 'simso.schedulers.P_EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.P_EDF2', 'name': 'simso.schedulers.P_EDF2'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.P_EDF_WF', 'name': 'simso.schedulers.P_EDF_WF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.P_RM', 'name': 'simso.schedulers.P_RM'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.PriD', 'name': 'simso.schedulers.PriD'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.RM', 'name': 'simso.schedulers.RM'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.RM_mono', 'name': 'simso.schedulers.RM_mono'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.RUN', 'name': 'simso.schedulers.RUN'},
{'required_proc_fields': [{'default': '1.0', 'type': 'float', 'name': 'speed'}], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.Static_EDF', 'name': 'simso.schedulers.Static_EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.U_EDF', 'name': 'simso.schedulers.U_EDF'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.WC_RUN', 'name': 'simso.schedulers.WC_RUN'},
{'required_proc_fields': [], 'required_fields': [], 'required_task_fields': [], 'display_name': 'simso.schedulers.WC_U_EDF', 'name': 'simso.schedulers.WC_U_EDF'}]
